-- AIverse Seed Data — 100+ Real AI Tools with GPS coordinates
-- Run this after schema.sql

INSERT INTO public.ai_tools (name, description, long_description, category, tags, pricing_model, price_starting, website_url, logo_url, founded_year, company, is_featured, upvotes, country_code, lat, lng) VALUES

-- ============================================================
-- TEXT GENERATION
-- ============================================================
('ChatGPT','The world''s most popular AI chatbot by OpenAI. Capable of writing, reasoning, coding, and much more.','ChatGPT is a large language model developed by OpenAI. It can assist with a wide range of tasks including writing, analysis, coding, math, creative projects, and general question-answering. Available in GPT-3.5 and GPT-4 variants, it features multi-turn conversation, image understanding (GPT-4V), code execution, and plugin integration.','Text Generation',ARRAY['chatbot','writing','reasoning','GPT-4','OpenAI','assistant'],'Freemium',20.00,'https://chat.openai.com','https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg',2022,'OpenAI',true,4821,'US',37.7749,-122.4194),

('Claude','Anthropic''s AI assistant known for nuanced reasoning, long-context understanding, and safety focus.','Claude is a family of AI models developed by Anthropic. Claude 3 (Haiku, Sonnet, Opus) excels at complex analysis, thoughtful writing, coding assistance, and long-document summarization with up to 200k token context windows. Designed with Constitutional AI principles for safety and helpfulness.','Text Generation',ARRAY['chatbot','writing','reasoning','long-context','Anthropic','safety'],'Freemium',20.00,'https://claude.ai','https://upload.wikimedia.org/wikipedia/commons/8/8a/Claude_AI_logo.svg',2021,'Anthropic',true,3654,'US',37.7749,-122.4194),

('Mistral','High-performance open source LLMs rivaling proprietary models in reasoning and efficiency.','Mistral AI develops state-of-the-art open source language models. Mistral 7B punches above its weight class for its size, while Mixtral 8x7B uses a Mixture of Experts (MoE) architecture. Mistral Large competes with GPT-4. All models are available under Apache 2.0 for local deployment, and via the La Plateforme API.','Text Generation',ARRAY['open source','LLM','efficient','MoE','API','self-hosted'],'Open Source',null,'https://mistral.ai','https://avatars.githubusercontent.com/u/145320053',2023,'Mistral AI',true,2543,'FR',48.8566,2.3522),

('Jasper','Enterprise AI writing platform for marketing teams to create on-brand content at scale.','Jasper is an AI writing platform built for marketing and enterprise use cases. It features Brand Voice to ensure consistent tone, Campaigns for multi-channel content creation, and integrations with SEO tools like Surfer. Templates cover ad copy, blog posts, email sequences, social media, and more.','Text Generation',ARRAY['marketing','copywriting','brand','SEO','enterprise','content creation'],'Paid',49.00,'https://jasper.ai','https://avatars.githubusercontent.com/u/77298741',2021,'Jasper AI',false,1654,'US',30.2672,-97.7431),

('Notion AI','AI writing assistant deeply integrated into Notion for summarizing, drafting, and editing.','Notion AI brings AI capabilities directly into the Notion workspace. It can summarize long documents, brainstorm ideas, draft content, fix grammar, translate text, and extract action items from meeting notes. The tight integration with Notion databases makes it particularly powerful for knowledge management workflows.','Productivity',ARRAY['writing','productivity','workspace','summarization','notes','collaboration'],'Freemium',10.00,'https://notion.so/product/ai','https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png',2023,'Notion Labs',false,2156,'US',37.7749,-122.4194),

('DeepSeek','Chinese open source LLM with GPT-4 level performance at a fraction of the training cost.','DeepSeek has released a series of open source large language models including DeepSeek-V2 and DeepSeek-Coder that achieve frontier performance while requiring significantly less compute to train. DeepSeek-V3 and R1 models have gained global attention for their exceptional reasoning abilities.','Text Generation',ARRAY['open source','Chinese','reasoning','coding','efficient','LLM'],'Open Source',null,'https://deepseek.com','https://avatars.githubusercontent.com/u/148330874',2023,'DeepSeek',true,3102,'CN',30.2741,120.1551),

('Grok','Elon Musk''s AI chatbot by xAI, integrated into X (Twitter) with real-time information access.','Grok is a conversational AI created by xAI with a rebellious personality and access to real-time data from X (formerly Twitter). Grok 2 features multimodal capabilities including image understanding and generation via Aurora. Available to X Premium+ subscribers.','Text Generation',ARRAY['chatbot','real-time','X','Twitter','Elon Musk','multimodal'],'Paid',16.00,'https://grok.x.ai','https://avatars.githubusercontent.com/u/160798232',2023,'xAI',false,2876,'US',34.0522,-118.2437),

('Llama','Meta''s open source family of LLMs — the most widely used foundation models in AI development.','Meta''s Llama family (Llama 2, Llama 3, Llama 3.1) are open source large language models that can be downloaded and run locally. They power thousands of fine-tuned models, products, and research projects. Llama 3.1 405B is competitive with GPT-4 at the frontier.','Text Generation',ARRAY['open source','Meta','foundation model','self-hosted','fine-tuning','Llama'],'Open Source',null,'https://llama.meta.com','https://avatars.githubusercontent.com/u/143898?s=200',2023,'Meta AI',false,3456,'US',37.4845,-122.1477),

('Gemma','Google''s family of lightweight, open source LLMs designed to run on device or in the cloud.','Gemma is a family of lightweight open source models from Google, built from the same research and technology as Gemini. Available in 2B and 7B parameter sizes, they are optimized for inference efficiency and can run on laptops or edge devices.','Text Generation',ARRAY['open source','Google','lightweight','on-device','efficient','foundation model'],'Open Source',null,'https://ai.google.dev/gemma','https://avatars.githubusercontent.com/u/1342004',2024,'Google',false,2103,'US',37.4220,-122.0841),

('Phi-3','Microsoft''s surprisingly capable small language models that punch far above their weight.','Microsoft''s Phi-3 family demonstrates that small language models can achieve high performance on reasoning and coding benchmarks. Phi-3-mini (3.8B) runs locally on phones, while Phi-3-medium (14B) achieves near-GPT-3.5 performance. Ideal for edge deployment and low-latency inference.','Text Generation',ARRAY['small model','Microsoft','on-device','efficient','reasoning','open source'],'Open Source',null,'https://azure.microsoft.com/en-us/products/phi-3','',2024,'Microsoft',false,1543,'US',47.6062,-122.3321),

('Writer','AI writing platform purpose-built for enterprises with strict compliance and brand requirements.','Writer is an enterprise-grade AI platform that combines LLMs with deep customization for brand voice, terminology, and compliance guardrails. It features Palmyra, a proprietary LLM family, plus Knowledge Graph for RAG, and integrations with enterprise tools like Salesforce, Workday, and Google Drive.','Text Generation',ARRAY['enterprise','writing','compliance','brand voice','RAG','B2B'],'Enterprise',null,'https://writer.com','https://avatars.githubusercontent.com/u/96614504',2020,'Writer',false,1234,'US',37.7749,-122.4194),

('Cohere','Enterprise AI platform with powerful text understanding, generation, and embeddings APIs.','Cohere provides NLP APIs for enterprise use cases including semantic search, summarization, classification, and generation. The Command R+ model excels at RAG-based question answering. Cohere''s embedding models power vector search in many enterprise products.','Text Generation',ARRAY['enterprise','NLP','embeddings','RAG','API','semantic search'],'Paid',null,'https://cohere.com','https://avatars.githubusercontent.com/u/54850923',2019,'Cohere',false,1876,'CA',43.6532,-79.3832),

('Perplexity','AI-powered search engine that provides cited, conversational answers in real time.','Perplexity AI is a conversational search engine that combines LLMs with real-time web search. Every answer is cited with sources, enabling users to verify information. Features include Copilot mode for guided research, focus modes (academic, YouTube, Reddit), collections, and a powerful API for developers.','Search',ARRAY['search','research','citations','real-time','web','Q&A'],'Freemium',20.00,'https://perplexity.ai','https://avatars.githubusercontent.com/u/110299016',2022,'Perplexity AI',true,3102,'US',37.7749,-122.4194),

-- ============================================================
-- IMAGE GENERATION
-- ============================================================
('Midjourney','Leading AI image generation model known for stunning artistic quality and photorealism.','Midjourney is a generative AI image synthesis service that creates art from natural language descriptions. Accessible primarily through Discord, it excels at creating cinematic, painterly, and photorealistic images. Version 6 supports text in images, improved anatomy, and high-res upscaling.','Image Generation',ARRAY['image generation','art','design','creative','Discord','photorealism'],'Paid',10.00,'https://midjourney.com','https://upload.wikimedia.org/wikipedia/commons/e/e6/Midjourney_Emblem.png',2021,'Midjourney, Inc.',true,4102,'US',37.7749,-122.4194),

('DALL-E 3','OpenAI''s image generation model with superior prompt understanding and native ChatGPT integration.','DALL-E 3 is OpenAI''s most advanced image generation model, built directly into ChatGPT Plus. It features significantly improved prompt adherence compared to previous versions, can render accurate text within images, and produces highly coherent visuals.','Image Generation',ARRAY['image generation','OpenAI','ChatGPT','art','design','API'],'Freemium',20.00,'https://openai.com/dall-e-3','https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg',2023,'OpenAI',false,2341,'US',37.7749,-122.4194),

('Stable Diffusion','Open source image generation model that runs locally or in the cloud with full customization.','Stable Diffusion is a latent text-to-image diffusion model capable of generating detailed images from text prompts. Being open-source, it can be run locally on consumer hardware, fine-tuned with custom datasets (LoRA, DreamBooth), and deployed via APIs. Available through AUTOMATIC1111, ComfyUI, and many commercial products.','Image Generation',ARRAY['image generation','open source','local','fine-tuning','LoRA','ComfyUI'],'Open Source',null,'https://stability.ai','https://avatars.githubusercontent.com/u/100950301',2022,'Stability AI',false,3215,'GB',51.5074,-0.1278),

('Adobe Firefly','Adobe''s commercially safe AI image generation integrated into Creative Cloud.','Adobe Firefly is Adobe''s family of AI image generation models, trained exclusively on licensed content, making it safe for commercial use. Integrated into Photoshop (Generative Fill), Illustrator (Generative Recolor), and Premiere Pro. Firefly 3 supports text-to-image, image-to-image, and generative fill.','Image Generation',ARRAY['commercial safe','Adobe','Creative Cloud','Photoshop','design','generative fill'],'Freemium',null,'https://firefly.adobe.com','https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Adobe_Firefly_wordmark.svg/512px-Adobe_Firefly_wordmark.svg.png',2023,'Adobe',false,2054,'US',37.3382,-121.8863),

('Ideogram','AI image generation with industry-leading text rendering inside generated images.','Ideogram 2.0 is a text-to-image model known for its exceptional ability to render legible, accurate text within generated images — a historically difficult challenge for diffusion models. It also excels at graphic design, logos, and typography-heavy compositions.','Image Generation',ARRAY['image generation','text rendering','typography','logos','design','graphics'],'Freemium',8.00,'https://ideogram.ai','https://avatars.githubusercontent.com/u/131270748',2023,'Ideogram AI',false,1876,'US',37.7749,-122.4194),

('Leonardo AI','Professional AI image generation platform with fine-tuning and an extensive model library.','Leonardo AI provides a web-based platform for generating and editing AI images with an emphasis on game assets, concept art, and product design. Features include Canvas editor, Universal Upscaler, 3D texture generation, AI video generation, and a library of community fine-tuned models.','Image Generation',ARRAY['image generation','game art','concept art','fine-tuning','platform','3D'],'Freemium',12.00,'https://leonardo.ai','https://avatars.githubusercontent.com/u/117860181',2022,'Leonardo AI',false,1654,'AU',-33.8688,151.2093),

('Flux','The fastest open source image generation model family with exceptional prompt adherence.','Flux by Black Forest Labs is a series of text-to-image models (Flux.1 Pro, Dev, Schnell) known for speed and prompt following accuracy. Flux.1 Schnell generates images in 1-4 steps. Available via API (Replicate, fal.ai) and as open weights.','Image Generation',ARRAY['image generation','open source','fast','prompt adherence','API','Black Forest Labs'],'Freemium',null,'https://blackforestlabs.ai','https://avatars.githubusercontent.com/u/171997969',2023,'Black Forest Labs',true,2876,'DE',52.5200,13.4050),

('Canva AI','AI-powered design features built into Canva''s popular graphic design platform.','Canva has integrated AI throughout its platform including text-to-image generation, Magic Eraser, Background Remover, Magic Resize, AI-powered presentations, and the Magic Studio suite. Used by over 150 million people worldwide for creating graphics, presentations, and social media content.','Image Generation',ARRAY['design','graphic design','social media','presentations','no-code','Magic Studio'],'Freemium',15.00,'https://canva.com/ai','https://upload.wikimedia.org/wikipedia/commons/b/bb/Canva_Logo.svg',2023,'Canva',false,2765,'AU',-33.8688,151.2093),

('Krea','Real-time AI image generation and enhancement for creative professionals.','Krea AI offers real-time image generation that updates as you draw or type, AI upscaling to 4K, and an expansive canvas for creative workflows. The real-time generation feature lets designers iterate visually at the speed of thought.','Image Generation',ARRAY['real-time','upscaling','creative','canvas','design','generation'],'Freemium',24.00,'https://krea.ai','https://avatars.githubusercontent.com/u/109574210',2022,'Krea AI',false,1234,'US',37.7749,-122.4194),

('Magnific','AI upscaling and image enhancement that adds extraordinary detail to images.','Magnific AI is an AI upscaling and enhancement tool that can increase image resolution up to 10x while adding photorealistic detail. It interprets the image context and hallucinate plausible high-res textures. Used extensively by photographers, artists, and VFX professionals.','Image Generation',ARRAY['upscaling','enhancement','detail','photography','VFX','resolution'],'Paid',39.00,'https://magnific.ai','https://avatars.githubusercontent.com/u/149099840',2023,'Magnific AI',false,1543,'ES',40.4168,-3.7038),

-- ============================================================
-- CODE
-- ============================================================
('GitHub Copilot','AI pair programmer that suggests code completions and entire functions in your IDE.','GitHub Copilot is an AI coding assistant powered by OpenAI Codex. It integrates into VS Code, JetBrains IDEs, Neovim, and more, providing inline code suggestions, whole-function completions, and chat assistance. Copilot X expands this with pull request summaries, docs generation, and CLI assistance.','Code',ARRAY['coding','IDE','autocomplete','GitHub','VS Code','pair programming'],'Paid',10.00,'https://github.com/features/copilot','https://github.githubassets.com/images/modules/site/copilot/copilot.png',2021,'GitHub (Microsoft)',true,3876,'US',47.6062,-122.3321),

('Cursor','The AI-first code editor built on VS Code with deep codebase understanding and multi-file editing.','Cursor is an AI-powered fork of VS Code designed for AI-assisted software development. It features Cmd+K for inline edits, a chat interface with codebase context (@codebase), multi-file editing (Composer), and uses frontier models (Claude, GPT-4). Cursor understands entire codebases, can apply diffs across files, and dramatically speeds up development.','Code',ARRAY['coding','IDE','VS Code','multi-file','codebase','editor'],'Freemium',20.00,'https://cursor.sh','https://avatars.githubusercontent.com/u/126759922',2022,'Anysphere',true,4540,'US',37.7749,-122.4194),

('v0','Vercel''s AI UI generation tool that creates React components from text and image prompts.','v0 by Vercel is a generative UI tool that creates production-ready React and Next.js components from natural language descriptions or screenshots. It uses Tailwind CSS and shadcn/ui by default, supports iterative refinement through conversation, and generates code that can be directly copied into projects.','Code',ARRAY['UI generation','React','Next.js','Tailwind','Vercel','components','shadcn'],'Freemium',20.00,'https://v0.dev','https://avatars.githubusercontent.com/u/14985020',2023,'Vercel',false,2765,'US',37.7749,-122.4194),

('Lovable','Full-stack AI app builder that creates and deploys production web apps from a single prompt.','Lovable is an AI software engineer that builds complete full-stack web applications from natural language descriptions. It uses React, Supabase, and Tailwind under the hood, supports GitHub sync, real-time collaboration, and one-click deployment. Formerly known as GPT Engineer.','Code',ARRAY['app builder','full-stack','React','Supabase','no-code','deployment'],'Freemium',20.00,'https://lovable.dev','https://avatars.githubusercontent.com/u/172027073',2023,'Lovable',false,2234,'SE',59.3293,18.0686),

('Tabnine','AI code completion tool with strong privacy features and on-premise deployment options.','Tabnine is an AI coding assistant that provides whole-line and full-function code completions. It supports all major programming languages and IDEs, with options for both cloud and on-premise deployment to meet enterprise privacy requirements. It can learn from your codebase privately.','Code',ARRAY['coding','autocomplete','privacy','on-premise','enterprise','IDE'],'Freemium',12.00,'https://tabnine.com','https://avatars.githubusercontent.com/u/21003344',2018,'Tabnine',false,1543,'IL',32.0853,34.7818),

('Codeium','Free AI code completion and chat for individual developers across 70+ programming languages.','Codeium offers free AI code completion and a chat assistant for developers. It supports 70+ programming languages, integrates with 40+ IDEs, and provides context-aware completions. The enterprise version (Windsurf) adds team features and codebase-level understanding.','Code',ARRAY['coding','free','70+ languages','autocomplete','chat','IDE'],'Freemium',null,'https://codeium.com','https://avatars.githubusercontent.com/u/98882517',2021,'Codeium',false,2102,'US',37.7749,-122.4194),

('Windsurf','The most powerful AI-native IDE from Codeium with deep agentic coding capabilities.','Windsurf (formerly Codeium Enterprise) is Codeium''s agentic IDE that goes beyond code completion. It features Cascade, an AI that can understand and modify entire codebases, run commands, browse documentation, and take multi-step actions to complete complex development tasks.','Code',ARRAY['coding','IDE','agentic','Codeium','Cascade','full-stack'],'Freemium',15.00,'https://codeium.com/windsurf','https://avatars.githubusercontent.com/u/98882517',2024,'Codeium',false,2543,'US',37.7749,-122.4194),

('Bolt.new','AI-powered full-stack web development environment in the browser by StackBlitz.','Bolt.new is an AI coding environment that runs entirely in the browser, powered by WebContainers. It can create, run, edit, and deploy full-stack applications without any local setup. Built on Claude Sonnet, it supports Next.js, Vite, Astro, and all major JavaScript frameworks.','Code',ARRAY['full-stack','browser','WebContainers','Next.js','deployment','no-setup'],'Freemium',20.00,'https://bolt.new','https://avatars.githubusercontent.com/u/728236',2024,'StackBlitz',false,2876,'US',37.7749,-122.4194),

('Replit AI','AI pair programmer built into Replit''s online IDE with ghostwriter and agent capabilities.','Replit AI (formerly Ghostwriter) is the AI assistant built into Replit''s cloud development environment. It features code completion, code explanation, error debugging, and an AI agent that can build and deploy complete apps. Especially popular with learners and for rapid prototyping.','Code',ARRAY['online IDE','coding','education','deployment','agent','beginner-friendly'],'Freemium',20.00,'https://replit.com/ai','https://avatars.githubusercontent.com/u/983194',2021,'Replit',false,2102,'US',37.7749,-122.4194),

('Devin','The world''s first autonomous AI software engineer that can plan and execute complex coding tasks.','Devin by Cognition AI is an autonomous AI software engineer capable of completing end-to-end software engineering tasks. It has its own shell, browser, and code editor, and can research documentation, fix bugs, build features, and deploy applications from a single high-level prompt.','Agent',ARRAY['autonomous','software engineer','coding','agentic','full-stack','Cognition'],'Enterprise',null,'https://cognition.ai','https://avatars.githubusercontent.com/u/151643625',2024,'Cognition AI',true,3241,'US',37.7749,-122.4194),

('Continue','Open source AI code assistant for VS Code and JetBrains with bring-your-own-model support.','Continue is an open source coding assistant that lets developers use any LLM (Claude, GPT-4, Ollama, etc.) within VS Code and JetBrains. Features include inline editing, code explanation, and a chat panel with codebase context. Fully customizable and privacy-first.','Code',ARRAY['open source','VS Code','JetBrains','BYOM','coding','privacy'],'Open Source',null,'https://continue.dev','https://avatars.githubusercontent.com/u/115789982',2023,'Continue Dev',false,1432,'US',37.7749,-122.4194),

('Aider','AI pair programming in the terminal that can edit multiple files simultaneously.','Aider is an open source command-line tool that lets developers chat with LLMs about their codebase and make coordinated edits across multiple files. It integrates with git, supports all major languages, and can work with GPT-4, Claude, and local models via Ollama.','Code',ARRAY['CLI','pair programming','multi-file','git','open source','terminal'],'Open Source',null,'https://aider.chat','https://avatars.githubusercontent.com/u/110145115',2023,'Aider',false,1876,'US',42.3601,-71.0589),

('Ollama','Run powerful open source LLMs locally on your machine with a simple CLI and API.','Ollama makes it easy to run large language models locally on macOS, Linux, and Windows. With a single command, you can pull and run models like Llama 3, Mistral, Gemma, Phi, and hundreds more. Ollama provides an OpenAI-compatible API, supports model customization via Modelfiles, and integrates with popular tools.','Code',ARRAY['local LLM','open source','CLI','API','Llama','privacy','self-hosted'],'Open Source',null,'https://ollama.com','https://avatars.githubusercontent.com/u/151674099',2023,'Ollama',false,3102,'US',37.7749,-122.4194),

-- ============================================================
-- AUDIO
-- ============================================================
('ElevenLabs','Hyper-realistic AI voice cloning and text-to-speech with emotional range and 32 languages.','ElevenLabs is the leading AI voice platform offering ultra-realistic text-to-speech, voice cloning from short samples, and multilingual dubbing. The VoiceLab allows creating custom voices, while Projects enables long-form audio production. Used by podcasters, audiobook publishers, game developers, and content creators globally.','Audio',ARRAY['voice synthesis','TTS','voice cloning','audio','dubbing','multilingual'],'Freemium',5.00,'https://elevenlabs.io','https://avatars.githubusercontent.com/u/104632225',2022,'ElevenLabs',true,2987,'US',37.7749,-122.4194),

('Suno','Create full songs with vocals, instruments, and lyrics from a simple text prompt.','Suno is an AI music generation platform that creates complete songs — including vocals, instrumentation, and lyrics — from text descriptions. Users can specify genre, mood, and style to generate studio-quality tracks in seconds. Features include custom lyrics input, song extension, and cover song creation.','Audio',ARRAY['music generation','song creation','vocals','lyrics','creative','audio'],'Freemium',10.00,'https://suno.com','https://avatars.githubusercontent.com/u/166285754',2023,'Suno AI',false,2234,'US',42.3601,-71.0589),

('Udio','AI music generation with exceptional audio quality and fine-grained style control.','Udio generates music with remarkable fidelity and creative control. Users can specify tempo, key, instruments, mood, and style references. It supports 30-second clips and a remix feature. Backed by major music industry investors and notable for its professional audio quality.','Audio',ARRAY['music generation','audio quality','style control','remix','creative','professional'],'Freemium',10.00,'https://udio.com','https://avatars.githubusercontent.com/u/161939866',2024,'Udio AI',false,1876,'US',37.7749,-122.4194),

('Whisper','OpenAI''s open source speech recognition model with near-human accuracy across 100 languages.','Whisper is an open-source automatic speech recognition (ASR) system trained on 680,000 hours of multilingual audio data. It supports transcription in 100+ languages and translation to English. Available in multiple model sizes (tiny to large-v3), it can be run locally or accessed via the OpenAI API.','Audio',ARRAY['speech recognition','transcription','translation','open source','multilingual','ASR'],'Open Source',null,'https://openai.com/research/whisper','https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg',2022,'OpenAI',false,2102,'US',37.7749,-122.4194),

('Descript','All-in-one podcast and video editor with AI transcription and voice cloning.','Descript is an audio and video editing tool that lets you edit media by editing text transcripts. Features include AI transcription, Studio Sound for noise removal, Overdub for AI voice cloning, Underlord AI for filler word removal and auto-cut, and screen recording with teleprompter.','Audio',ARRAY['podcast','video editing','transcription','voice cloning','screen recording','audio'],'Freemium',24.00,'https://descript.com','https://avatars.githubusercontent.com/u/15781300',2017,'Descript',false,1654,'US',37.7749,-122.4194),

('Podcastle','AI podcast creation and editing platform with studio-quality voice enhancement.','Podcastle is a podcast creation tool with AI-powered features including Magic Dust (studio-quality audio in one click), text-to-speech with custom AI voices, transcription, and a web-based recording studio. Supports multi-track recording, clip-based editing, and automated noise removal.','Audio',ARRAY['podcast','recording','transcription','voice enhancement','editing','audio'],'Freemium',14.99,'https://podcastle.ai','https://avatars.githubusercontent.com/u/86437249',2019,'Podcastle',false,987,'AM',40.1872,44.5152),

('PlayHT','AI voice generation with ultra-realistic cloning and 900+ voices in 142 languages.','PlayHT offers text-to-speech and voice cloning with an extensive library of 900+ AI voices across 142 languages. Enterprise features include real-time TTS API, custom voice training from 2 minutes of audio, and a voice agent builder for conversational AI applications.','Audio',ARRAY['TTS','voice cloning','900+ voices','API','multilingual','voice agent'],'Freemium',39.00,'https://play.ht','https://avatars.githubusercontent.com/u/63929315',2019,'PlayHT',false,1234,'US',37.7749,-122.4194),

('Murf AI','Professional AI voiceover studio with 120+ realistic voices for content creators.','Murf AI is a text-to-speech platform focused on professional voiceover production. It offers 120+ ultra-realistic AI voices, pitch control, speed adjustment, emphasis settings, and background music. Popular for explainer videos, eLearning content, and product demos.','Audio',ARRAY['voiceover','TTS','120+ voices','eLearning','video','professional'],'Freemium',29.00,'https://murf.ai','https://avatars.githubusercontent.com/u/78527836',2020,'Murf AI',false,1102,'US',37.7749,-122.4194),

('Lalal.ai','AI audio stem separation tool that splits any song into instruments and vocals instantly.','LALAL.AI uses AI to separate audio stems from any song or recording — isolating vocals, drums, bass, piano, guitar, synthesizers, and more. Useful for remixing, karaoke creation, music production, and extracting samples. Supports batch processing and an API for developers.','Audio',ARRAY['stem separation','music production','remixing','vocals','karaoke','API'],'Paid',null,'https://lalal.ai','https://avatars.githubusercontent.com/u/74524869',2020,'LALAL.AI',false,876,'CY',35.1264,33.4299),

-- ============================================================
-- VIDEO
-- ============================================================
('Runway','Professional AI video generation and editing suite trusted by filmmakers and creators.','Runway is a multimodal AI research company building tools for creative professionals. Gen-3 Alpha enables text-to-video and image-to-video generation with high temporal consistency. Additional features include background removal, motion tracking, inpainting, and an AI Magic Tools suite.','Video',ARRAY['video generation','text-to-video','editing','creative','filmmaking','Gen-3'],'Freemium',15.00,'https://runwayml.com','https://avatars.githubusercontent.com/u/46653948',2018,'Runway AI',true,2654,'US',40.7128,-74.0060),

('Synthesia','Create professional AI videos with realistic avatars and voiceovers in 120+ languages.','Synthesia is a leading AI video creation platform that enables creating professional videos with AI avatars — no cameras, actors, or studios required. Features include 160+ AI avatars, 120+ languages, custom avatar creation, screen recording, and LMS integrations. Widely used for corporate training, marketing, and localized content.','Video',ARRAY['avatar','video creation','corporate','training','multilingual','no-camera'],'Paid',22.00,'https://synthesia.io','https://avatars.githubusercontent.com/u/49798602',2017,'Synthesia',false,1876,'GB',51.5074,-0.1278),

('HeyGen','AI video platform for creating personalized video messages with talking avatars and voice cloning.','HeyGen is an AI video generation platform focused on personalization at scale. Create videos with photorealistic avatars, clone your own voice, and translate videos into 40+ languages while preserving lip sync. Used for sales outreach, marketing personalization, and multilingual content creation.','Video',ARRAY['avatar','video','personalization','voice cloning','lip sync','multilingual'],'Freemium',29.00,'https://heygen.com','https://avatars.githubusercontent.com/u/91740701',2020,'HeyGen',false,1765,'US',37.3382,-121.8863),

('Kling','Chinese AI video generation model that creates highly realistic, physically accurate videos.','Kling AI by Kuaishou is a text-to-video and image-to-video generation model known for exceptional physical simulation, realistic motion, and high-resolution output up to 1080p. It supports 5-second and 10-second video generation and has rapidly become competitive with Sora.','Video',ARRAY['video generation','Chinese','physical simulation','realistic','1080p','text-to-video'],'Freemium',10.00,'https://klingai.com','https://avatars.githubusercontent.com/u/166540500',2024,'Kuaishou',false,2543,'CN',39.9042,116.4074),

('Pika','Fast and easy AI video generation for social media creators.','Pika is a consumer-focused AI video generation platform that makes it easy to create short, shareable video clips from text or images. Pika 2.0 features lip sync, video ingredients for character consistency, and special effects like explosions and squish. Optimized for viral short-form content.','Video',ARRAY['video generation','social media','short-form','lip sync','effects','easy to use'],'Freemium',8.00,'https://pika.art','https://avatars.githubusercontent.com/u/133756104',2023,'Pika Labs',false,1987,'US',37.7749,-122.4194),

('Luma AI','Photorealistic AI video generation and 3D capture with the Dream Machine.','Luma AI offers two flagship products: Dream Machine for text-to-video generation with smooth, photorealistic output, and NeRF-based 3D capture for turning videos into 3D models. Dream Machine 1.5 produces 120-frame videos with excellent motion quality.','Video',ARRAY['video generation','3D capture','photorealistic','NeRF','Dream Machine','3D models'],'Freemium',29.99,'https://lumalabs.ai','https://avatars.githubusercontent.com/u/71985832',2021,'Luma AI',false,2102,'US',37.7749,-122.4194),

('D-ID','Create digital humans and AI video avatars from a single photo for presentations and marketing.','D-ID is an AI platform specializing in digital human creation. It can animate still photos to speak, generate talking avatar videos from text, and create AI-powered interactive video agents. Used by marketing teams, eLearning creators, and enterprises for personalized video at scale.','Video',ARRAY['digital human','talking avatar','photo animation','video','marketing','personalized'],'Freemium',16.00,'https://d-id.com','https://avatars.githubusercontent.com/u/61839839',2017,'D-ID',false,1432,'IL',32.0853,34.7818),

('Captions','AI-powered video editing app focused on auto-captions, eye contact correction, and reels.','Captions is an AI video editing app for creators that auto-generates styled captions, corrects eye contact using AI, removes filler words, and suggests B-roll. Available on iOS and Android, it''s designed for social media creators who want to produce polished content quickly.','Video',ARRAY['captions','social media','eye contact','TikTok','reels','mobile'],'Freemium',19.99,'https://captions.ai','https://avatars.githubusercontent.com/u/85843568',2021,'Captions AI',false,1234,'US',40.7128,-74.0060),

('Colossyan','AI video creation platform built for learning and development professionals.','Colossyan Creator lets L&D teams create training videos with AI avatars without cameras, studios, or actors. It supports 70+ languages, custom avatar creation, SCORM export, and integrations with major LMS platforms. Features automatic translations and interactive video elements.','Video',ARRAY['eLearning','training','avatar','L&D','SCORM','enterprise'],'Paid',27.00,'https://colossyan.com','https://avatars.githubusercontent.com/u/92820093',2020,'Colossyan',false,876,'HU',47.4979,19.0402),

('Sora','OpenAI''s text-to-video AI that generates cinematic, highly realistic videos up to one minute.','Sora is OpenAI''s text-to-video model capable of generating detailed, realistic, and imaginative videos up to 60 seconds in length. It creates consistent characters, scenes, and motion. Currently available to ChatGPT Plus and Pro subscribers with usage limits.','Video',ARRAY['video generation','OpenAI','text-to-video','cinematic','realistic','long-form'],'Paid',20.00,'https://openai.com/sora','https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg',2024,'OpenAI',true,3456,'US',37.7749,-122.4194),

-- ============================================================
-- MULTIMODAL
-- ============================================================
('Gemini','Google''s multimodal AI model with deep integration into Google Workspace and Search.','Gemini is Google''s flagship AI model family (Ultra, Pro, Nano). It natively understands text, images, audio, video, and code. Available through Google AI Studio, and integrated into Workspace products. Gemini 1.5 Pro supports a 1M token context window.','Multimodal',ARRAY['multimodal','Google','chatbot','image understanding','Workspace','long context'],'Freemium',19.99,'https://gemini.google.com','https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Google_Gemini_logo.svg/1200px-Google_Gemini_logo.svg.png',2023,'Google',true,2987,'US',37.4220,-122.0841),

('GPT-4o','OpenAI''s most capable and fastest multimodal model for vision, audio, and text.','GPT-4o ("omni") is OpenAI''s flagship multimodal model that natively handles text, audio, images, and video in real time. It speaks with natural emotion, reads visual inputs, and has 128K context. Available in ChatGPT and via API, it represents the convergence of all modalities into a single model.','Multimodal',ARRAY['multimodal','vision','audio','OpenAI','real-time','omni'],'Freemium',20.00,'https://openai.com/gpt-4o','https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg',2024,'OpenAI',true,4102,'US',37.7749,-122.4194),

('Claude 3.5 Sonnet','Anthropic''s best model combining vision, reasoning, and coding in a fast, affordable package.','Claude 3.5 Sonnet achieves top performance across coding (SWE-bench), visual reasoning, and general intelligence benchmarks while being faster and cheaper than Claude 3 Opus. Features include computer use (controlling a desktop via API), vision, and a 200K context window.','Multimodal',ARRAY['vision','coding','reasoning','computer use','Anthropic','multimodal'],'Freemium',20.00,'https://claude.ai','https://upload.wikimedia.org/wikipedia/commons/8/8a/Claude_AI_logo.svg',2024,'Anthropic',true,3654,'US',37.7749,-122.4194),

-- ============================================================
-- AGENT
-- ============================================================
('LangChain','The leading framework for building LLM-powered applications and agentic workflows.','LangChain is an open-source framework for developing applications powered by language models. It provides abstractions for chains, agents, memory, retrievers, and tools. LangChain Expression Language (LCEL) enables composable pipelines, while LangSmith provides observability and evaluation.','Agent',ARRAY['framework','LLM','RAG','agents','open source','Python','JavaScript'],'Open Source',null,'https://langchain.com','https://avatars.githubusercontent.com/u/126733545',2022,'LangChain',false,2876,'US',37.7749,-122.4194),

('AutoGPT','Pioneering autonomous AI agent that breaks down goals into tasks and executes them independently.','AutoGPT is one of the first autonomous AI agent frameworks, using GPT-4 as its core reasoning engine. It can browse the internet, write and execute code, manage files, and interact with external services to accomplish long-horizon goals. The project spawned the modern AI agents movement.','Agent',ARRAY['autonomous agent','GPT-4','automation','open source','task planning','self-directed'],'Open Source',null,'https://agpt.co','https://avatars.githubusercontent.com/u/130738209',2023,'Significant Gravitas',false,1987,'US',37.7749,-122.4194),

('CrewAI','Framework for orchestrating role-playing AI agents that collaborate to complete complex tasks.','CrewAI is a framework for creating teams of AI agents with defined roles, goals, and tools. Agents collaborate sequentially or in parallel, delegating tasks to specialists. Used to build complex automation pipelines, research assistants, and multi-step workflows.','Agent',ARRAY['multi-agent','collaboration','role-playing','orchestration','Python','automation'],'Open Source',null,'https://crewai.com','https://avatars.githubusercontent.com/u/170677839',2023,'CrewAI',false,2103,'US',37.7749,-122.4194),

('AutoGen','Microsoft''s framework for building multi-agent AI systems with conversational intelligence.','AutoGen is an open source framework from Microsoft Research that enables building next-generation LLM applications using multiple agents that converse with each other to solve tasks. Supports human-in-the-loop workflows, code execution, and tool use.','Agent',ARRAY['multi-agent','Microsoft','conversational','code execution','orchestration','open source'],'Open Source',null,'https://microsoft.github.io/autogen','https://avatars.githubusercontent.com/u/6154722',2023,'Microsoft Research',false,2341,'US',47.6062,-122.3321),

('n8n','Workflow automation platform with native AI integrations and self-hosted option.','n8n is a fair-code workflow automation platform that connects 400+ apps and services. Its AI features include LangChain integration, AI Agent nodes, and vector database connections for building complex AI pipelines. Supports both cloud and self-hosted deployment.','Agent',ARRAY['workflow automation','no-code','LangChain','integrations','self-hosted','pipelines'],'Freemium',24.00,'https://n8n.io','https://avatars.githubusercontent.com/u/45487711',2019,'n8n GmbH',false,1876,'DE',52.5200,13.4050),

('Make','No-code automation platform with AI-powered scenario building for 1000+ apps.','Make (formerly Integromat) is a visual automation platform connecting 1000+ apps. Its AI features include ChatGPT integration, AI-powered text extraction, and the ability to build complex multi-step automations. Used by businesses of all sizes to automate repetitive workflows.','Agent',ARRAY['no-code','automation','1000+ apps','visual','workflow','integrations'],'Freemium',9.00,'https://make.com','https://avatars.githubusercontent.com/u/44617685',2012,'Make',false,1543,'CZ',50.0755,14.4378),

('Zapier AI','AI-enhanced workflow automation connecting 7000+ apps with natural language setup.','Zapier connects 7000+ apps and has added AI-powered features including natural language Zap creation, AI-powered tables, chatbots, and an AI Actions API. The AI features make automation accessible to non-technical users who can describe workflows in plain English.','Agent',ARRAY['automation','7000+ apps','no-code','natural language','workflow','enterprise'],'Freemium',29.99,'https://zapier.com','https://avatars.githubusercontent.com/u/2219786',2011,'Zapier',false,1987,'US',37.7749,-122.4194),

('Relevance AI','No-code platform for building and deploying AI agents and multi-step AI workflows.','Relevance AI is a platform for building AI agents and tools without coding. Users create custom AI agents by combining tools, LLMs, and logic. Agents can browse the web, send emails, update CRMs, and execute complex business workflows autonomously.','Agent',ARRAY['no-code','agent builder','workflow','tools','business automation','LLM'],'Freemium',19.00,'https://relevanceai.com','https://avatars.githubusercontent.com/u/88671981',2020,'Relevance AI',false,1102,'AU',-33.8688,151.2093),

-- ============================================================
-- SEARCH & DATA
-- ============================================================
('You.com','AI search engine with multimodal answers, code execution, and research modes.','You.com is an AI search engine offering multiple modes: Smart for general search, Research for deep multi-source synthesis, Create for image generation, and Code for programming assistance. It aggregates web results and synthesizes them with LLMs for comprehensive, cited answers.','Search',ARRAY['search','AI search','multimodal','research','code','web'],'Freemium',20.00,'https://you.com','https://avatars.githubusercontent.com/u/77489369',2020,'You.com',false,1234,'US',37.7749,-122.4194),

('Kagi','Privacy-focused premium search engine with AI summarization and zero ads.','Kagi is a paid search engine that offers ad-free, unbiased search results. Its AI features include Universal Summarizer for any URL, FastGPT for quick AI answers, and Lenses for domain-specific search. Users control their own search results by customizing source rankings.','Search',ARRAY['privacy','no ads','search','summarization','premium','unbiased'],'Paid',10.00,'https://kagi.com','https://avatars.githubusercontent.com/u/45773849',2017,'Kagi',false,1102,'US',37.7749,-122.4194),

('Exa','The AI-native web search API built for LLMs with semantic search capabilities.','Exa (formerly Metaphor) is a search API designed specifically for AI applications. It uses neural search to find the most semantically relevant web pages, rather than keyword matching. Used by AI developers to give their LLMs access to current web information.','Search',ARRAY['API','semantic search','LLM','neural search','developer','web crawling'],'Paid',null,'https://exa.ai','https://avatars.githubusercontent.com/u/132540537',2022,'Exa',false,876,'US',37.7749,-122.4194),

('Consensus','AI search engine for scientific research that finds evidence in peer-reviewed papers.','Consensus searches through 200M+ scientific papers and uses AI to extract and synthesize the key findings. It tells you what the scientific consensus is on a topic, with citations to original research. Invaluable for researchers, students, medical professionals, and science communicators.','Search',ARRAY['research','science','papers','evidence-based','citations','academic'],'Freemium',9.99,'https://consensus.app','https://avatars.githubusercontent.com/u/101406924',2021,'Consensus',false,987,'US',37.7749,-122.4194),

('Tableau AI','AI-powered analytics and data visualization platform with Einstein Copilot.','Tableau AI (part of Salesforce) integrates generative AI throughout the Tableau platform via Einstein Copilot. Users can ask questions in natural language to generate visualizations, receive AI-powered explanations of data trends, and automate reporting workflows.','Data',ARRAY['data visualization','analytics','Salesforce','natural language','BI','enterprise'],'Enterprise',null,'https://tableau.com','https://avatars.githubusercontent.com/u/1032336',2003,'Salesforce (Tableau)',false,1102,'US',37.7749,-122.4194),

('DataRobot','Enterprise AI platform for automated machine learning and MLOps.','DataRobot is an enterprise AI platform that automates the end-to-end machine learning lifecycle: data preparation, model training, selection, deployment, and monitoring. Its AutoML capabilities enable data scientists to build and deploy models faster while maintaining governance and compliance.','Data',ARRAY['AutoML','enterprise','MLOps','machine learning','data science','automation'],'Enterprise',null,'https://datarobot.com','https://avatars.githubusercontent.com/u/4855353',2012,'DataRobot',false,987,'US',42.3601,-71.0589),

-- ============================================================
-- PRODUCTIVITY
-- ============================================================
('Otter.ai','AI meeting assistant that transcribes, summarizes, and captures action items in real time.','Otter.ai is an AI note-taking tool that joins Zoom, Google Meet, and Teams meetings to transcribe conversations in real time. It generates meeting summaries, extracts action items, identifies speakers, and integrates with calendars and productivity tools.','Productivity',ARRAY['transcription','meeting notes','Zoom','action items','summaries','calendar'],'Freemium',16.99,'https://otter.ai','https://avatars.githubusercontent.com/u/32756349',2016,'Otter.ai',false,1876,'US',37.7749,-122.4194),

('Mem','AI-powered personal knowledge management and note-taking app with automatic organization.','Mem is a note-taking tool that uses AI to automatically organize notes, surface relevant information, and generate drafts. It connects scattered information across notes to provide context and help users leverage their accumulated knowledge.','Productivity',ARRAY['notes','knowledge management','organization','AI writing','personal','memory'],'Freemium',14.99,'https://mem.ai','https://avatars.githubusercontent.com/u/78024044',2020,'Mem Labs',false,876,'US',37.7749,-122.4194),

('Beautiful.ai','AI-powered presentation tool that automatically designs slides as you add content.','Beautiful.ai is a presentation software that uses AI to enforce design best practices automatically. As users add content, slides adjust their layout, typography, and spacing intelligently. Features include 60+ smart slide types, team collaboration, and brand theming.','Productivity',ARRAY['presentations','design','slides','no-design-skills','business','team'],'Paid',12.00,'https://beautiful.ai','https://avatars.githubusercontent.com/u/12770967',2016,'Beautiful.ai',false,876,'US',37.7749,-122.4194),

('Gamma','AI presentation and document generator that turns prompts into polished slides.','Gamma is an AI tool that creates polished presentations, documents, and webpages from a single text prompt. It handles layout, design, imagery, and formatting automatically. Features collaborative editing, version history, analytics, and custom branding.','Productivity',ARRAY['presentations','documents','AI generation','design','collaboration','one-click'],'Freemium',10.00,'https://gamma.app','https://avatars.githubusercontent.com/u/90137858',2021,'Gamma App',false,1543,'US',37.7749,-122.4194),

('Grammarly','AI writing assistant for grammar, style, tone, and clarity across all your apps.','Grammarly is an AI writing assistant that helps users communicate more effectively. It checks grammar, spelling, punctuation, clarity, engagement, and delivery in real time across web browsers, Microsoft Office, and Google Docs. GrammarlyGO adds generative AI for drafting and rewriting.','Productivity',ARRAY['writing','grammar','editing','tone','clarity','browser extension'],'Freemium',30.00,'https://grammarly.com','https://avatars.githubusercontent.com/u/6706938',2009,'Grammarly',false,2543,'US',37.7749,-122.4194),

('Speechify','AI text-to-speech app that reads any document, PDF, or web page aloud at up to 4.5x speed.','Speechify converts any text content — PDFs, emails, web articles, Google Docs — into natural-sounding audio narrated by AI voices. It supports 30+ languages, adjustable speeds, and highlighting. Popular with students, busy professionals, and people with reading difficulties.','Productivity',ARRAY['text-to-speech','reading','accessibility','PDF','speed reading','education'],'Freemium',139.00,'https://speechify.com','https://avatars.githubusercontent.com/u/46819609',2017,'Speechify',false,1234,'US',34.0522,-118.2437),

('Fireflies.ai','AI meeting assistant that records, transcribes, and analyzes conversations for teams.','Fireflies.ai is an AI meeting intelligence platform that joins virtual meetings to capture, transcribe, and analyze conversations. It extracts action items, topics discussed, sentiment, and insights. Integrates with 40+ apps including Salesforce, Slack, and project management tools.','Productivity',ARRAY['meetings','transcription','analysis','action items','CRM','team intelligence'],'Freemium',10.00,'https://fireflies.ai','https://avatars.githubusercontent.com/u/60264428',2016,'Fireflies.ai',false,1102,'US',37.7749,-122.4194),

('Copy.ai','AI copywriting tool for generating marketing copy, blog content, and social media posts.','Copy.ai is an AI writing tool with 90+ templates for marketing copy, blog posts, email campaigns, social media captions, and more. Its brand voice feature ensures consistency, while the Workflows feature automates multi-step content creation pipelines.','Productivity',ARRAY['copywriting','marketing','templates','blog','social media','email'],'Freemium',49.00,'https://copy.ai','https://avatars.githubusercontent.com/u/77246832',2020,'Copy.ai',false,1102,'US',37.7749,-122.4194),

('Loom AI','AI-powered async video messaging with auto-generated titles, summaries, and chapters.','Loom is an async video messaging tool for teams, and Loom AI adds automatic video titles, summaries, next steps, task detection, and filler word removal. Users record their screen + webcam and share a link. Acquired by Atlassian in 2023.','Productivity',ARRAY['async video','screen recording','meetings','summaries','team communication','Atlassian'],'Freemium',15.00,'https://loom.com','https://avatars.githubusercontent.com/u/10454044',2015,'Loom (Atlassian)',false,1543,'US',37.7749,-122.4194),

('Tome','AI storytelling and presentation tool that creates narrative-driven slides and documents.','Tome is an AI-native document and presentation tool that emphasizes storytelling. Its AI generates entire presentations from a prompt, creates image galleries, embeds live data, and produces narrative-driven content that goes beyond traditional slides.','Productivity',ARRAY['presentations','storytelling','AI generation','documents','narrative','design'],'Freemium',16.00,'https://tome.app','https://avatars.githubusercontent.com/u/107278596',2020,'Magical Tome',false,987,'US',37.7749,-122.4194),

('Reclaim.ai','AI calendar assistant that automatically schedules tasks, habits, and meetings.','Reclaim.ai is an AI scheduling tool that connects to Google Calendar and intelligently blocks time for tasks, habits, breaks, and flexible meetings. It adapts to changes in real time, defending your focus time while maximizing availability for collaboration.','Productivity',ARRAY['calendar','scheduling','time management','habits','Google Calendar','focus time'],'Freemium',10.00,'https://reclaim.ai','https://avatars.githubusercontent.com/u/64088413',2019,'Reclaim.ai',false,876,'US',37.7749,-122.4194),

('Perplexity Pages','AI-powered long-form article creation with citations and structured research reports.','Perplexity Pages allows users to create comprehensive, AI-generated articles and research reports with structured sections, citations, and visuals. Reports can be published and shared, making it useful for research summaries, briefings, and educational content.','Productivity',ARRAY['research','articles','citations','reports','publishing','AI writing'],'Freemium',20.00,'https://perplexity.ai/collections','https://avatars.githubusercontent.com/u/110299016',2024,'Perplexity AI',false,876,'US',37.7749,-122.4194),

('Wordtune','AI writing companion that suggests rephrasing options to make text clearer and more engaging.','Wordtune is an AI writing tool focused on improving existing text through smart rewriting suggestions. It offers multiple rephrasing options for any sentence, can expand or shorten text, change tone (formal/casual), and translate into English from other languages.','Productivity',ARRAY['rewriting','paraphrasing','editing','clarity','tone','writing'],'Freemium',13.99,'https://wordtune.com','https://avatars.githubusercontent.com/u/68020440',2020,'AI21 Labs',false,765,'IL',32.0853,34.7818);
